### ISSUE TITLE
Issues connecting to CosmosDB

### ISSUE THREAD

**Issue by tattooedDev** [vapor/fluent-mongo-driver#42] opened 2021-05-24 19:07 UTC
Hello, I'm having trouble connecting my app to an Azure CosmosDB.
I can't share the exact connection string since it's my employer's, but here's a redacted version:

``` swift
mongodb://{username}:{password}@{host}:{port}/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@{appName}@
```

Using this approach doesn't work at all:
``` swift
try app.databases.use(.mongo(connectionString: "mongodb://{username}:{password}@{host}:{port}/?ssl=true"), as: .mongo)
```

When I try to use this I get the following errors:
```
[ ERROR ] Couldn't find or create a connection to MongoDB with the requested specification
[ ERROR ] Couldn't find or create a connection to MongoDB with the requested specification
[ WARNING ] No hosts could be connected with, therefore no queries can be sent at the moment: The connection string could not be used to connect to a host
Solution(s):
- Check if your hosts are online, not undergoing maintenance
- Check your connection strings for any errors in configuration
- Check if your server is whitelisted when using MongoDB atlas
- If using MongoDB atlas, make sure you're connecting with SRV
```

Could someone tell me what's going on there?

I tested the connection string in the mongo shell, where it worked fine. I also tried using MongoKitten, where it didn't work. But using the official [Mongo Swift Driver](https://docs.mongodb.com/drivers/swift/) works fine as well.

Thanks in advance for any help.

**Comment by 0xTim** [comment] 2021-05-25 13:11
cc @Joannis

**Comment by Joannis** [comment] 2021-05-25 13:17
Hey @thedan84, I haven't tried connecting to CosmosDB, and wouldn't know what's different about their connection phase. I'm creating an azure account so that I can dive into the issue.

**Comment by Joannis** [comment] 2021-05-25 13:51
Hey @thedan84 , I seem to have found the cause of the issue. CosmosDB is violating the handshake specification, by providing an epoch timestamp rather than a BSON timestamp. I'm currently debating in what way to support this violation without affecting other code behaviour (too much).

**Comment by tattooedDev** [comment] 2021-05-25 14:43
@Joannis Thanks for the quick response. 👍🏼
I hope it's not too much of an effort.

**Comment by Joannis** [comment] 2021-05-25 15:57
It's a bit more complicated than just one spec violation. I'll try to see what all the differences are.

**Comment by Joannis** [comment] 2021-06-01 11:56
Hey @thedan84, I've found CosmosDB to be at the _least_ a major pain in the ass, but I can send queries now. 

A couple notes, for the interested (or people that for some insane reason want their own MongoDB+CosmosDB driver):

1. CosmosDB does not support OpMessage, even though it's supported API level indicates it does. If you for some "foolish" reason expect to use OpMessage, you're greeted by the amazing concept of "let's just close the connection without an error".
2. CosmosDB' MongoDB API is basically just a proxy to HTTP, and the errors are just as nice as you'd expect - an HTTP message dumped into the `errmsg` string.
3. While it's clearly documented in the BSON spec, cosmos DB expects you to read `Date` as an epoch timestamp, even tough `Date` is the formal definition by spec of these values. This is particularly noticeable in the `isMaster` handshake. So drivers just need to deal with the spec violation.
4. Even though MongoDB and SASL spec both state you can send "String", "Binary representing UTF-8 of a String" or "Binary representing the base64-ed value of the UTF-8". CosmosDB only accepts the second one. Any attempts at base64-ed data, or regular String data, is met by a confusing error.

Once all of these are resolved, I can do inserts and find ops. But don't expect the powerful MongoDB features such as aggregates to work fully as expected.

**Comment by Joannis** [comment] 2021-06-01 11:57
If you're on discord, please contact me :)

**Comment by Joannis** [comment] 2021-06-08 16:17
Hey @thedan84 , I happened to get an email this morning regarding the future of MongoDB for drivers. They're making some big changes, the most critical of which is the deprecation of their old protocol. That protocol has already been replaced in MongoDB 3.6, dating back to 2017.

Unfortunately for you, CosmosDB is quite heavily reliant on that old protocol right now. It uses OP_QUERY rather than OP_MESSAGE, as mentioned in my previous comment. That implies that MongoKitten will need to run in a customised legacy mode for CosmosDB to work. While I currently have a branch targeting CosmosDB, it's highly unlikely that I'll implement such code it in the official releases.

On the upside:
1. CosmosDB has an HTTP API
2. You can build a custom client that supports CosmosDB using `MongoKittenCore`, which will still maintain the necessary legacy protocol specification.

**Comment by tattooedDev** [comment] 2021-06-11 05:14
@Joannis Thanks for the update. I'll see what I'll do then. Maybe I just use the official driver for work then. I got it working with that, but wasn't overly happy with the result. Thanks anyway for investigating and all the updates.

**Comment by 0xTim** [comment] 2021-06-12 04:14
I'll close this for now, feel free to reopen off you have any more queries!

**Closed as completed by 0xTim** 2021-06-12 04:14 UTC
Labels: bug
